### PR TITLE
parsing variadic functions, avoiding empty list error

### LINKED ISSUE #23: Variadic functions don't parse
Hnix doesn't currently parse variadic (`...`) arguments:

```
GHCi, version 7.10.1: http://www.haskell.org/ghc/  :? for help
[1 of 3] Compiling Nix.Types        ( Nix/Types.hs, interpreted )
[2 of 3] Compiling Nix.Parser.Library ( Nix/Parser/Library.hs, interpreted )
[3 of 3] Compiling Nix.Parser       ( Nix/Parser.hs, interpreted )
Ok, modules loaded: Nix.Parser, Nix.Parser.Library, Nix.Types.
*Nix.Parser> parseNixString "{x, ...}: x"
Failure <string>:1:3: error: expected: "=",
    ., letter or digit
{x, ...}: x<EOF> 
  ^              
*Nix.Parser> 
```

Also this isn't represented in the AST. This is the way that `simple-nix` encapsulates this:

``` haskell
data FuncArgs
  = Arg Name
  | Kwargs (HashMap Name (Maybe NixExpr)) Bool (Maybe Name)
  deriving (Show, Eq)
```

Where the boolean indicates if it's variadic, and the `Maybe Name` indicates whether it has an `@`. I think it might be sufficient to modify the `FormalParamSet` type to add a flag indicating if it's variadic or not, and add machinery to parse that.

### PR DESCRIPTION
**Pull request by adnelson**
@jwiegley fixes #23 

I know I'm a collaborator now, but I figured I'd still put things in for code review. :)

### CODE REVIEW

File: Nix/Parser.hs [hunk 1]
```diff
@@ -56,8 +56,9 @@ nixHasAttr term = build <$> term <*> optional (reservedOp "?" *> nixSelector) wh
   build t Nothing = t
   build t (Just s) = Fix $ NHasAttr t s
 
-nixOpArg :: Parser NExpr
-nixOpArg = nixSelect $ choice
+-- | A self-contained unit.
+nixTerm :: Parser NExpr
```
Comment (adnelson) [inline Nix/Parser.hs:60]: I just renamed this because I felt it was a little clearer (also it reflects the `term` nomenclature used in the `nixExpr` function)

File: Nix/Eval.hs [hunk 2]
```diff
@@ -16,16 +16,17 @@ import           Prelude hiding (mapM, sequence)
 buildArgument :: Formals NValue -> NValue -> NValue
 buildArgument paramSpec arg = either error (Fix . NVSet) $ case paramSpec of
     FormalName name -> return $ Map.singleton name arg
-    FormalSet s -> lookupParamSet s
-    FormalLeftAt name s -> Map.insert name arg <$> lookupParamSet s
-    FormalRightAt s name -> Map.insert name arg <$> lookupParamSet s
+    FormalSet s Nothing -> lookupParamSet s
+    FormalSet s (Just name) -> Map.insert name arg <$> lookupParamSet s
```
Comment (adnelson) [inline Nix/Eval.hs:20]: `nix-instantiate --parse` makes no distinction between `@`s at left or right, so I figured this was unnecessary information to retain. Let me know if you feel otherwise.

Comment (adnelson) [inline Nix/Eval.hs:20]:
```
➜  nix-instantiate --parse -E '{x}@y: x'
({ x } @ y: x)
➜  nix-instantiate --parse -E 'y@{x}: x'
({ x } @ y: x)
```

File: Nix/Eval.hs [hunk 3]
```diff
@@ -16,16 +16,17 @@ import           Prelude hiding (mapM, sequence)
...
       where err = "Could not find " ++ show k
 
-    lookupParamSet (FormalParamSet s) = case arg of
-      Fix (NVSet env) -> Map.traverseWithKey (go env) s
-      _               -> Left "Unexpected function environment"
+    lookupParamSet fps = case fps of
+      FixedParamSet s -> case arg of
+        Fix (NVSet env) -> Map.traverseWithKey (go env) s
+        _               -> Left "Unexpected function environment"
+      _ -> error "Can't yet handle variadic param sets"
```
Comment (adnelson) [inline Nix/Eval.hs:29]: This is me just being lazy: it might be trivial to add this; I just wanted to make the type checker happy.

File: Nix/Types.hs [hunk 4]
```diff
@@ -104,7 +104,9 @@ stripIndent xs = NString Indented . removePlainEmpty . mergePlain . unsplitLines
   ls = stripEmptyOpening $ splitLines xs
   ls' = map (dropSpaces minIndent) ls
 
-  minIndent = minimum . map (countSpaces . mergePlain) . stripEmptyLines $ ls
+  minIndent = case stripEmptyLines ls of
```
Comment (adnelson) [inline Nix/Types.hs:107]: This fixes an occasional `Prelude.minimum: empty list` error, which (I assume) occurs when a multiline string is empty.

**Comment by jwiegley** [comment]
Hi @adnelson, I'm moving to Sacramento tomorrow (from Illinois), and won't have any more time to review things until the weekend of the 3rd.  Until then!

**Comment by adnelson** [comment]
Ah cool, well I'm just going to merge this then since at the very least it adds functionality. Good luck with the move!

**Comment by jwiegley** [comment]
Sounds good, I'll look over some of the changes after I get back, but until then feel free to consider yourself a co-maintainer, and make whatever decisions you feel add value for your use of the project.
