### PR TITLE
Builtins.div cannot divide by 0

### LINKED ISSUE #277: builtins.div handling of zero
`hnix` differs from `nix-instantiate` in three cases that I've found; one of these is almost certainly a `nix` bug.

```
[nix-shell:~/Documents/Haskell/hnix]$ ./dist/build/hnix/hnix --eval --expr 'builtins.div 4 0'
179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137216

[nix-shell:~/Documents/Haskell/hnix]$ ./dist/build/hnix/hnix --eval --expr 'builtins.div 4 0.0'
Infinity

[nix-shell:~/Documents/Haskell/hnix]$ dist/build/hnix/hnix --eval --expr 'builtins.div (builtins.div 4 0.1) 3'
13.333333

[nix-shell:~/Documents/Haskell/hnix]$ nix-instantiate --eval --expr 'builtins.div 4 0'
error: division by zero, at (string):1:1

[nix-shell:~/Documents/Haskell/hnix]$ nix-instantiate --eval --expr 'builtins.div 4 0.0'
error: division by zero, at (string):1:1

[nix-shell:~/Documents/Haskell/hnix]$ nix-instantiate --eval --expr 'builtins.div (builtins.div 4 0.1) 3'
error: value is a float while an integer was expected, at (string):1:1
```

Note, this was tested on commit 30dcb1cf98da9df75f3665885956407fe52ebdce

### PR DESCRIPTION
**Pull request by picnoir**
Add a pre-condition on builtin.div to prevent division by zero.

Fixes #277.

### CODE REVIEW

File: src/Nix/Builtins.hs [hunk 1]
```diff
@@ -356,11 +356,14 @@ mul_ x y = x >>= \x' -> y >>= \y' -> case (x', y') of
 
 div_ :: MonadNix e m => m (NValue m) -> m (NValue m) -> m (NValue m)
 div_ x y = x >>= \x' -> y >>= \y' -> case (x', y') of
-    (NVConstant (NInt x),   NVConstant (NInt y))   ->
+    (NVConstant (NInt x),   NVConstant (NInt y))   | y /= 0 ->
```
Comment (jwiegley) [inline src/Nix/Builtins.hs:359]: All looks good to me.

**Review by jwiegley — APPROVED** [review]
